version: 2

sources:
  - name: raw
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    config:
      enabled: true
    tables:
      - name: orders
        columns:
          - name: o_orderkey
            tests:
              - unique
              - not_null
      - name: lineitem
        columns:
          - name: l_orderkey
            tests:
              - relationships:
                  to: source('raw', 'orders')
                  field: o_orderkey

                  